/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EnReadme: typeof import('./components/EnReadme.md')['default']
    Header: typeof import('./components/Header.vue')['default']
    KnowledgeGraph: typeof import('./components/KnowledgeGraph.vue')['default']
    MonacoEditor: typeof import('./components/MonacoEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SourceCard: typeof import('./components/SourceCard.vue')['default']
    ToolCallCard: typeof import('./components/ToolCallCard.vue')['default']
    TopMenu: typeof import('./components/TopMenu.vue')['default']
    VoiceInteraction: typeof import('./components/VoiceInteraction.vue')['default']
    ZhReadme: typeof import('./components/ZhReadme.md')['default']
  }
}
